name: Enterprise DevSecOps CICD Pipeline
on:
 push:
   branches:
     - qa
   paths:
     - client/**
     - server/**
     - .github/workflows/qa-cicd.yml
     
jobs:
  gitleaks-scan:
    name: Gitleak Scan
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Source Code
       uses: actions/checkout@v4
    
     - name: Gitleaks Scan
       run: |
         docker run --rm \
           -v "${{ github.workspace }}:/repo" \
           zricethezav/gitleaks:latest detect \
           --source=/repo \
           --report-format=json \
           --report-path=/repo/gitleaks-report-json \
           --redact \
           --exit-code 0

     - name: Upload Gitleaks report
       uses: actions/upload-artifact@v5
       with:
         name: gitleak-report
         path: gitleaks-report.json
         if-no-files-found: warn


           









       
     
